name: TrChat
main: me.arasple.mc.trchat.TrChat

api-version: 1.13
version: ${version}

description: Advanced Minecraft Chat Control

built-time: ${built}

softdepend:
  - PlaceholderAPI

authors:
  - Arasple
  - 寒雨
